name: 'Run woke fuzzing tests'
description: ''
author: 'oogali'
inputs:
  working-directory:
    description: ''
    required: false

runs:
  using: 'docker'
  image: Dockerfile
  args:
    - ${{ inputs.working-directory }}
